### ISSUE TITLE
Slack links still point to old Score Slack and invite url

### ISSUE THREAD

**Issue by astromechza** [score-spec/score.dev#5]
Since moving into CNCF Slack, we need to update all the links in this repo that mention Score with a link to both the channel <https://cloud-native.slack.com/archives/C07DN0D1UCW> but also to the CNCF invite link <https://slack.cncf.io/> which allows folks to invite themselves.

**Comment by MiirzaBaig** [comment]
Shall i work on this to update ?

**Comment by FL303** [comment]
Thanks @MiirzaBaig, already solved: https://github.com/score-spec/score.dev/pull/7
